version: '3'
services:
  flux:
    image: fluxcapacitorio/flux-capacitor-test:latest
  proxy:
    image: fluxcapacitorio/flux-capacitor-proxy
    environment:
      - FLUX_URL=http://flux:8080
      - PROXY_PORT=8080
    ports:
      - 8080:8080
  app:
    build:
      context: app
    environment:
      - FLUX_URL=http://flux:8080
