version: '3'
services:
  flux-capacitor:
    image: fluxcapacitorio/flux-capacitor-test:latest

  app:
    depends_on:
      - flux-capacitor
    build:
      context: ./app/.
    image: app:tag
    environment:
      - MESSAGING_ENDPOINT=ws://flux-capacitor:8888

  web:
    depends_on:
      - flux-capacitor
    build:
      context: ./web/.
    image: web:tag
    environment:
      - MESSAGING_ENDPOINT=ws://flux-capacitor:8888
    ports:
      - "8090:8080"
      - "5100:5005" #debugging

volumes:
  config:
    driver: local
  flux-capacitor:
    driver: local
