version: '3'
services:
  flux-capacitor:
    build:
      context: .
      dockerfile: Dockerfile-flux-capacitor
      args:
        - FLUX_VERSION=736
        - ARTIFACTORY_URL=https://artifactory.portbase.io/artifactory
        - ARTIFACTORY_USER=readonly:${ARTIFACTORY_ENCRYPTED_PASSWORD}
    image: flux-capacitor:tag
    environment:
      - DROP_DATABASE=${dropDatabase:-false}
      - POSTGRES_PASSWORD=example
    volumes:
      - ./postgres-data:/var/lib/postgresql/data

  app:
    depends_on:
      - flux-capacitor
    build:
      context: ./app/.
    image: app:tag
    environment:
      - MESSAGING_ENDPOINT=ws://flux-capacitor:8080

  web:
    depends_on:
      - flux-capacitor
    build:
      context: ./web/.
    image: web:tag
    environment:
      - MESSAGING_ENDPOINT=ws://flux-capacitor:8080
    ports:
      - "8090:8080"
      - "5100:5005" #debugging

volumes:
  config:
    driver: local
  flux-capacitor:
    driver: local
