name: Deploy app

on:
  push:
    branches: [ replacewithmaster ]

jobs:
  deploy:
    env:
      DOCKER_REPO: fluxcapacitorio
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

      - name: Install Java and Maven
        uses: actions/setup-java@v1
        with:
          java-version: 14

      - name: Run Maven build
        run: mvn -B install

      - name: Login to docker hub
        uses: actions-hub/docker/login@master
        env:
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}

      - name: Docker build
        run: docker build -t $DOCKER_REPO/${GITHUB_REPOSITORY#*/}:$GITHUB_SHA -t $DOCKER_REPO/${GITHUB_REPOSITORY#*/}:latest ./app

      - name: Push to docker hub
        uses: actions-hub/docker@master
        with:
          args: push $DOCKER_REPO/${GITHUB_REPOSITORY#*/}

      - name: Deploy client to sloppy.io
        env:
          SLOPPY_APITOKEN: ${{ secrets.SLOPPY_APITOKEN }}
          BASIC_AUTH_PW: ${{ secrets.BASIC_AUTH_PW }}
          ENCRYPTION_KEY: ${{ secrets.ENCRYPTION_KEY }}
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: Bearer $SLOPPY_APITOKEN" \
          -X PATCH -d '{"domain":{"uri":"'${GITHUB_REPOSITORY#*/}.apps.flux-capacitor.io'","redirectHttps":true,"hstsHeader":true},"ssl":true,"mem":2048,"image":"'$DOCKER_REPO/${GITHUB_REPOSITORY#*/}:$GITHUB_SHA'","instances":1,"port_mappings":[{"container_port":8080}],"env":{"MESSAGING_ENDPOINT":"ws://app.service.flux-capacitor.admin1.node.intern:8080","DOCKER_ENVIRONMENT":"production","ENCRYPTION_KEY":"'$ENCRYPTION_KEY'"}}' \
          "https://api.sloppy.io/v1/apps/flux-capacitor/services/clients/apps/${GITHUB_REPOSITORY#*/}"
