name: Deploy elastic

on:
  push:
    branches: [ deploy-elastic ]

jobs:
  deploy:
    env:
      DOCKER_REPO: fluxcapacitorio
    runs-on: ubuntu-latest
    steps:
      - name: Deploy elastic to sloppy.io
        env:
          SLOPPY_APITOKEN: ${{ secrets.SLOPPY_APITOKEN }}
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: Bearer $SLOPPY_APITOKEN" \
          -X PATCH -d '{"mem":2048,"image":"elasticsearch:7.1.1","instances":1,"port_mappings":[{"container_port":9200}, {"container_port":9300}], "env":{ "node.name":"'${GITHUB_REPOSITORY#*/}-es'", "discovery.type":"single-node", "http.compression":"false", "logger.level":"ERROR", "cluster.name":"'${GITHUB_REPOSITORY#*/}-elasticsearch'"},"volumes":[{"container_path":"/usr/share/elasticsearch/data","size":"16GB"}]}' \
          "https://api.sloppy.io/v1/apps/flux-capacitor/services/elastic/apps/elasticsearch"

      - name: Deploy kibana to sloppy.io
        env:
          SLOPPY_APITOKEN: ${{ secrets.SLOPPY_APITOKEN }}
        run: |
          curl -H "Content-Type: application/json" -H "Authorization: Bearer $SLOPPY_APITOKEN" \
          -X PATCH -d '{"domain":{"uri":"'${GITHUB_REPOSITORY#*/}-kibana.apps.flux-capacitor.io'","redirectHttps":true,"hstsHeader":true, "basicAuth": "Authentication:admin:$1$9b1TiuWC$ANUCDEILB..h5ccnjZCiI/"},"ssl":true,"port_mappings":[{"container_port":5601}], "mem":2048,"image":"kibana:7.1.1","instances":1, "env":{ "ELASTICSEARCH_HOSTS":"http://elasticsearch.elastic.flux-capacitor.admin1.node.intern:9200"}}' \
          "https://api.sloppy.io/v1/apps/flux-capacitor/services/elastic/apps/kibana"
